### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by theaspect** [D3rty/software_engineering_repo#9]
1. Именование методов, параметров, переменных, классов не соответствует стандарту
2. Смысла во вложенных условиях нет, ты всё равно выходишь из программы https://github.com/D3rty/software_engineering_repo/blob/master/src/d3rty/AAA_app/Main.java#L22
3. Подавляется исключение, его нужно пробрасывать наружу https://github.com/D3rty/software_engineering_repo/blob/master/src/d3rty/AAA_app/Security.java#L26 соответственно 28 строка не нужна
4. Сделай ифы плоскими а не вложенными https://github.com/D3rty/software_engineering_repo/blob/master/src/d3rty/AAA_app/Try_AAA.java#L11
   вместо
   
   ```
   if(x){
   }else{
   if(y){
   }else{
   }
   }
   ```
   
   делай
   
   ```
   if(x){
   }else if(y){
   }else{
   }
   ```

**Comment by d3ple** [comment]
**1.** Классы, методы, поля, переменные отформатированы в соответствии стандартам
**2.** и **4.** IF ELSE теперь плоские
**3.** Добавлен return для исключения
